//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assistant.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 助手 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动发送 的本地化字符串。
        /// </summary>
        public static string AutoTransmit {
            get {
                return ResourceManager.GetString("AutoTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动换行 的本地化字符串。
        /// </summary>
        public static string AutoWrap {
            get {
                return ResourceManager.GetString("AutoWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率 的本地化字符串。
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验位 的本地化字符串。
        /// </summary>
        public static string CheckBits {
            get {
                return ResourceManager.GetString("CheckBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验位错误 的本地化字符串。
        /// </summary>
        public static string CheckBitsError {
            get {
                return ResourceManager.GetString("CheckBitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除↓ 的本地化字符串。
        /// </summary>
        public static string ClearDown {
            get {
                return ResourceManager.GetString("ClearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清屏 的本地化字符串。
        /// </summary>
        public static string ClearScreen {
            get {
                return ResourceManager.GetString("ClearScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除↑ 的本地化字符串。
        /// </summary>
        public static string ClearUp {
            get {
                return ResourceManager.GetString("ClearUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 的本地化字符串。
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位 的本地化字符串。
        /// </summary>
        public static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位错误 的本地化字符串。
        /// </summary>
        public static string DataBitsError {
            get {
                return ResourceManager.GetString("DataBitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开 的本地化字符串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入发送内容 的本地化字符串。
        /// </summary>
        public static string EnterContent {
            get {
                return ResourceManager.GetString("EnterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex接收 的本地化字符串。
        /// </summary>
        public static string HexReceive {
            get {
                return ResourceManager.GetString("HexReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十六进制发送 的本地化字符串。
        /// </summary>
        public static string HexSend {
            get {
                return ResourceManager.GetString("HexSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex发送 的本地化字符串。
        /// </summary>
        public static string HexTransmit {
            get {
                return ResourceManager.GetString("HexTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略接收 的本地化字符串。
        /// </summary>
        public static string IgnoreReceive {
            get {
                return ResourceManager.GetString("IgnoreReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志模式 的本地化字符串。
        /// </summary>
        public static string LogMode {
            get {
                return ResourceManager.GetString("LogMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫雷 的本地化字符串。
        /// </summary>
        public static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有连接的客户端 的本地化字符串。
        /// </summary>
        public static string NoClient {
            get {
                return ResourceManager.GetString("NoClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的十六进制字符串 的本地化字符串。
        /// </summary>
        public static string PleaseInputHex {
            get {
                return ResourceManager.GetString("PleaseInputHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先打开串口 的本地化字符串。
        /// </summary>
        public static string PleaseOpenSerial {
            get {
                return ResourceManager.GetString("PleaseOpenSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先打开连接 的本地化字符串。
        /// </summary>
        public static string PleaseOpenSocket {
            get {
                return ResourceManager.GetString("PleaseOpenSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议类型 的本地化字符串。
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收字节数 的本地化字符串。
        /// </summary>
        public static string ReceiveBytes {
            get {
                return ResourceManager.GetString("ReceiveBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位计数 的本地化字符串。
        /// </summary>
        public static string ResetCount {
            get {
                return ResourceManager.GetString("ResetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收/发送帧数 的本地化字符串。
        /// </summary>
        public static string RxTxFrames {
            get {
                return ResourceManager.GetString("RxTxFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时发送 的本地化字符串。
        /// </summary>
        public static string ScheduledSend {
            get {
                return ResourceManager.GetString("ScheduledSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送间隔 的本地化字符串。
        /// </summary>
        public static string SendInterval {
            get {
                return ResourceManager.GetString("SendInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送目标 的本地化字符串。
        /// </summary>
        public static string SendTarget {
            get {
                return ResourceManager.GetString("SendTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口 的本地化字符串。
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络 的本地化字符串。
        /// </summary>
        public static string Socket {
            get {
                return ResourceManager.GetString("Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位 的本地化字符串。
        /// </summary>
        public static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位错误 的本地化字符串。
        /// </summary>
        public static string StopBitsError {
            get {
                return ResourceManager.GetString("StopBitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送字节数 的本地化字符串。
        /// </summary>
        public static string TransmitBytes {
            get {
                return ResourceManager.GetString("TransmitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新完成 的本地化字符串。
        /// </summary>
        public static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
